<a href="https://colab.research.google.com/github/koushikpr/Machine-Learning-Prerequisites/blob/TensorFlow-Tutorial/TensorFlow_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

# **TensorFlow Basics**


---



Tensors are n dimensional array representation

In [5]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
print(x)
#shape of the tensor
print(x.shape)
#data type it holds
print(x.dtype)


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


1. Operations on tensor

In [17]:
y = tf.constant([[1., 4., 9.],
                 [40., 5., 66.]])
# adding 
print(x+y)
#Scaling
print(5*x)
#Transpose
print(tf.transpose(x))
#concatenate
print(tf.concat([x,y],axis=0))#tf.concat([tf1,....tfn],axis=upto dimension-1) 
#convert to pdf
print(tf.nn.softmax(x,axis=-1))
#sum everything up
print(tf.reduce_sum(x))


tf.Tensor(
[[ 2.  6. 12.]
 [44. 10. 72.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 1.  4.  9.]
 [40.  5. 66.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]], shape=(2, 3), dtype=float32)
tf.Tensor(21.0, shape=(), dtype=float32)


2. Utilizing the GPU for optimized working

In [19]:
if tf.config.list_physical_devices('GPU'):
  print('YES')
else:
    print("NO")

NO


3. Creating mutable Variables

In [32]:
var = tf.Variable([1,2,3])
print(var)
new = var
new.assign([4,5,6])
print(new)
#adding/subtracting to the previous values
print(var.assign_add([10,20,30]))
print(var.assign_sub([1,1,1]))
#converting to numpy
print(var.numpy())
#converting to tensor
print(tf.convert_to_tensor(var))
#highest index
print(tf.argmax(var))
#reshaping
print(tf.reshape(var,[3,1]))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([14, 25, 36], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([13, 24, 35], dtype=int32)>
[13 24 35]
tf.Tensor([13 24 35], shape=(3,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(
[[13]
 [24]
 [35]], shape=(3, 1), dtype=int32)


4. Multiplying tensors in matrice format VS elementwise

In [51]:
a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])#matrice of 2x3
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])#matrice of 3x2
c = tf.matmul(a, b)
print(c.numpy()) # matrice of 2x2
x=tf.reshape(b,[2,3]) # matching vector b(3x2) to vector a(2x3)
print(a*x)#multiplying elements of respective indexes

[[22. 28.]
 [49. 64.]]
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)


# **Automated Differentiation**

---



In [59]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
  y = x**2

dy = tape.gradient(y,x)
print(dy)

w = tf.Variable(tf.random.normal((3,2)))
print(w)
b = tf.Variable(tf.zeros(2,dtype=tf.float32))
print(b)
x= [[1,2,3]]
with tf.GradientTape(persistent=True) as tape:
  y = x@w+b
  loss = tf.reduce_mean(y**2)

[dlw,dlb] = tape.gradient(loss,[w,b])
print(dlw,dlb)

tf.Tensor(6.0, shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-1.8109758 , -1.6473049 ],
       [-0.44288102, -0.4863753 ],
       [-0.18886766,  0.3907121 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>
tf.Tensor(
[[-3.2633407 -1.4479191]
 [-6.5266814 -2.8958383]
 [-9.790022  -4.3437576]], shape=(3, 2), dtype=float32) tf.Tensor([-3.2633407 -1.4479191], shape=(2,), dtype=float32)


# **Understanding Graphs in Tensors**

---



In order to process data till now, we require a python intepreter interface, But if we want to utilize this data without the intepreter or export it in a form of readable datasheet(ex:*.csv files) We can convert .Tensor variables to datasheets with the help of tf.Graph( In tensorflow Graphs are data structures)
To Create Graphs in Tensors We have a few steps

Step 1: Setup

In [1]:
import tensorflow as tf
import datetime as dt
import timeit

Step 2: Creating a tf.function to generates a graph

In [10]:
# Define a Python function performing a function xy+b
def basefunc(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x


# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

#Creating a variable using tf.function that performs the function and generates a graph
a_function_that_uses_a_graph = tf.function(basefunc)


#Calling the function directly 
fwog = basefunc(x1, y1, b1).numpy()
# Calling the function created by tf.function
fwg = a_function_that_uses_a_graph(x1, y1, b1)

#Both perform the sae function yet one contains the graph and one doesnt
print(fwg==fwog)

#Creating a tf.function using decorator
@tf.function
def tensfunc(x):
  y = tf.constant([[2.0], [3.0]])
  b = tf.constant(4.0)

  return basefunc(x,y,b)

#Calling using decorator generates a graph for both basefunc and tensfunc
tensfunc(tf.constant([[1.0, 2.0]])).numpy()


tf.Tensor([[ True]], shape=(1, 1), dtype=bool)


array([[12.]], dtype=float32)

Step 3: Converting tf.functions to graphs

In [16]:
tensfunc.get_concrete_function(x1).graph.as_graph_def()


node {
  name: "x"
  op: "Placeholder"
  attr {
    key: "_user_specified_name"
    value {
      s: "x"
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 2
        }
      }
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 1
          }
        }
        tensor_content: "\000\000\000@\000\000@@"
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 4.0
      }
    }
  }
}
node {
  name: "M

# **Tf.Functions**

---



1. Polymorphism :
tf.function can generate many graphs depeending on the input signature(data types)

In [23]:
tensfunc(tf.constant([[1.0, 2.0]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

2. Eagerly vs graphically: tf.functions can be set to run without generating graph(eagerly) 

In [ ]:
#running eagerly settings
tf.config.run_functions_eagerly(True)
#running graphically settings
tf.config.run_functions_eagerly(False)
# graphically takes a lot of load

Best Practise of tf.function

1. It may take some time to get used to the behavior of Function. To get started quickly, first-time users should play around with decorating toy functions with @tf.function to get experience with going from eager to graph execution.
2. Toggle between eager and graph execution early and often with tf.config.run_functions_eagerly to pinpoint if/ when the two modes diverge.
3. Create tf.Variables outside the Python function and modify them on the inside. The same goes for objects that use tf.Variable, like keras.layers, keras.Models and tf.optimizers.
4. Avoid writing functions that depend on outer Python variables, excluding tf.Variables and Keras objects. 
5. Prefer to write functions which take tensors and other TensorFlow types as input.
6. You can pass in other object types but be careful! Include as much computation as possible under a tf.function to maximize the performance gain. For example, decorate a whole training step or the entire training loop.




Timing of Graph Functions vs Eager Function

In [29]:
#Using Graphs
tf.config.run_functions_eagerly(False)
print('Graphs:',timeit.timeit(lambda: tensfunc(tf.constant([[1.0, 2.0]])),number=1000))
#Using Eager
tf.config.run_functions_eagerly(True)
print('Eager:',timeit.timeit(lambda: tensfunc(tf.constant([[1.0, 2.0]])),number=1000))



Graphs: 0.7734685890000037
Eager: 0.24355980699965585
